language: node_js

dist: trusty

node_js:
   - node

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --base-href=/wall-pi/ --prod --no-progress
  - cp dist/wall-pi/index.html dist/wall-pi/404.html
  - mv -f dist/wall-pi/config-live dist/wall-pi/config # Enable live config

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: dist/wall-pi